package exception_handing;

import java.io.IOException;

public class Exception_Test_1 {

	public static void main(String[] args)throws IOException {
		
		//To understand about Arithmetic Exception
		int a=10,b=0,ans;
		ans=a/b; // Exception araised and developer is not able to resolve it
		System.out.println("Answer is "+ans);
			
	
	}

}
